-- New Core database and history. Never baseline an existing Identity/Profile database into this migration.
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM pg_catalog.pg_class c
        JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace
        WHERE n.nspname IN ('identity','profile','channels')
        AND c.relkind IN ('r','p','v','m','S','f')
    ) THEN
        RAISE EXCEPTION 'Core requires empty domain schemas; non-empty legacy schemas need an explicit data import';
    END IF;
END $$;

CREATE SCHEMA IF NOT EXISTS identity;
CREATE SCHEMA IF NOT EXISTS profile;
CREATE SCHEMA IF NOT EXISTS channels;

CREATE TABLE identity.accounts (
    user_id VARCHAR(64) PRIMARY KEY,
    email VARCHAR(320) NOT NULL,
    normalized_email VARCHAR(320) NOT NULL UNIQUE,
    handle VARCHAR(25) NOT NULL,
    canonical_handle VARCHAR(25) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at_utc TIMESTAMPTZ NOT NULL
);

CREATE TABLE identity.sessions (
    session_id UUID PRIMARY KEY,
    user_id VARCHAR(64) NOT NULL REFERENCES identity.accounts(user_id) ON DELETE CASCADE,
    credential_hash CHAR(64) NOT NULL UNIQUE,
    created_at_utc TIMESTAMPTZ NOT NULL,
    expires_at_utc TIMESTAMPTZ NOT NULL,
    revoked_at_utc TIMESTAMPTZ,
    CHECK (expires_at_utc > created_at_utc)
);
CREATE INDEX identity_session_user_idx ON identity.sessions(user_id, expires_at_utc);

CREATE TABLE identity.rate_limit_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bucket_type VARCHAR(32) NOT NULL,
    bucket_hash CHAR(64) NOT NULL,
    source_key_hash CHAR(64),
    occurred_at_utc TIMESTAMPTZ NOT NULL
);
CREATE INDEX identity_rate_limit_window_idx ON identity.rate_limit_events(bucket_type,bucket_hash,occurred_at_utc DESC);
CREATE UNIQUE INDEX identity_registration_key_rate_idx ON identity.rate_limit_events(bucket_type,bucket_hash,source_key_hash) WHERE source_key_hash IS NOT NULL;

CREATE SCHEMA IF NOT EXISTS profile;

CREATE TABLE profile.profiles (
    user_id VARCHAR(64) PRIMARY KEY REFERENCES identity.accounts(user_id) ON DELETE CASCADE,
    display_name VARCHAR(50) NOT NULL,
    bio VARCHAR(300) NOT NULL DEFAULT '',
    avatar_key VARCHAR(100),
    profile_version BIGINT NOT NULL DEFAULT 0,
    created_at_utc TIMESTAMPTZ NOT NULL,
    updated_at_utc TIMESTAMPTZ NOT NULL
);

CREATE TABLE profile.avatar_uploads (
    upload_id_hash CHAR(64) PRIMARY KEY,
    user_id VARCHAR(64) NOT NULL REFERENCES identity.accounts(user_id) ON DELETE CASCADE,
    object_key VARCHAR(100) NOT NULL UNIQUE,
    content_type VARCHAR(32) NOT NULL CHECK (content_type IN ('image/jpeg','image/png','image/gif')),
    expires_at_utc TIMESTAMPTZ NOT NULL,
    created_at_utc TIMESTAMPTZ NOT NULL
);
CREATE INDEX profile_avatar_upload_expiry_idx ON profile.avatar_uploads(expires_at_utc);


CREATE TABLE channels.channels (
    channel_id VARCHAR(64) PRIMARY KEY,
    owner_user_id VARCHAR(64) NOT NULL UNIQUE REFERENCES identity.accounts(user_id) ON DELETE CASCADE,
    description VARCHAR(300) NOT NULL DEFAULT '',
    banner_uri TEXT,
    channel_version BIGINT NOT NULL DEFAULT 0 CHECK (channel_version >= 0),
    created_at_utc TIMESTAMPTZ NOT NULL,
    updated_at_utc TIMESTAMPTZ NOT NULL,
    UNIQUE (channel_id,owner_user_id)
);

CREATE TABLE identity.registrations (
    registration_id VARCHAR(64) PRIMARY KEY,
    idempotency_key_hash CHAR(64) NOT NULL UNIQUE,
    request_fingerprint CHAR(64) NOT NULL,
    user_id VARCHAR(64) NOT NULL UNIQUE REFERENCES identity.accounts(user_id),
    channel_id VARCHAR(64) NOT NULL UNIQUE,
    created_at_utc TIMESTAMPTZ NOT NULL,
    retain_until_utc TIMESTAMPTZ NOT NULL,
    CHECK (retain_until_utc > created_at_utc),
    FOREIGN KEY (channel_id,user_id) REFERENCES channels.channels(channel_id,owner_user_id)
);
CREATE INDEX identity_registration_retention_idx ON identity.registrations(retain_until_utc);

-- Published read contracts. Write ownership stays in each module's repository.
CREATE VIEW identity.public_accounts AS SELECT user_id,handle FROM identity.accounts;
CREATE VIEW profile.public_profiles AS
    SELECT user_id,display_name,bio,avatar_key,profile_version,updated_at_utc FROM profile.profiles;
