-- Discovery (SPEC-07, ADR-008). Extends Core without rewriting applied migrations.
CREATE SCHEMA IF NOT EXISTS discovery;

-- Published read contract of Channels: public columns only, like identity.public_accounts and profile.public_profiles.
CREATE VIEW channels.public_channels AS
    SELECT channel_id, owner_user_id, channel_version FROM channels.channels;

-- Public projection of Streaming (one row per stream configuration). Streaming stays the authority of state; this
-- table is derived and reconstructible from the private cut. A row is replaced only by a greater projection_version.
CREATE TABLE discovery.stream_projection (
    stream_id VARCHAR(64) PRIMARY KEY CHECK (stream_id ~ '^[A-Za-z0-9_-]{1,64}$'),
    channel_id VARCHAR(64) NOT NULL UNIQUE CHECK (channel_id ~ '^[A-Za-z0-9_-]{1,64}$'),
    projection_version BIGINT NOT NULL CHECK (projection_version >= 1),
    discovery_position BIGINT NOT NULL CHECK (discovery_position >= 1),
    content_hash CHAR(64) NOT NULL,
    metadata_version BIGINT NOT NULL CHECK (metadata_version >= 1),
    title TEXT NOT NULL CHECK (btrim(title) <> ''),
    normalized_title TEXT NOT NULL,
    category_id VARCHAR(64) NOT NULL,
    category_name TEXT NOT NULL,
    tags JSONB NOT NULL DEFAULT '[]'::jsonb,
    session_id VARCHAR(64),
    stream_generation BIGINT NOT NULL CHECK (stream_generation >= 0),
    session_version BIGINT CHECK (session_version >= 1),
    status VARCHAR(16) NOT NULL CHECK (status IN ('OFFLINE','PREPARING','LIVE','ENDED')),
    availability VARCHAR(16) NOT NULL CHECK (availability IN ('PLAYABLE','RECONNECTING','OFFLINE')),
    started_at_utc TIMESTAMPTZ,
    state_observed_at_utc TIMESTAMPTZ NOT NULL,
    viewer_count INTEGER NOT NULL CHECK (viewer_count >= 0),
    count_version BIGINT NOT NULL CHECK (count_version >= 0),
    viewer_count_observed_at_utc TIMESTAMPTZ,
    received_at_utc TIMESTAMPTZ NOT NULL,
    applied_at_utc TIMESTAMPTZ NOT NULL,
    -- A reachable stream always has a live session; only OFFLINE may lack one.
    CHECK (availability = 'OFFLINE' OR
           (status = 'LIVE' AND session_id IS NOT NULL AND session_version IS NOT NULL AND started_at_utc IS NOT NULL))
);
CREATE INDEX discovery_projection_ranking_idx
    ON discovery.stream_projection (viewer_count DESC, started_at_utc DESC, stream_id) WHERE availability = 'PLAYABLE';

-- Deduplication window for delivered events (identity and hash only: Streaming publishes one observation per
-- configuration every 2 s, so payloads are not kept). Purged after the retry window by a scheduled task.
CREATE TABLE discovery.inbox_events (
    event_id VARCHAR(64) PRIMARY KEY CHECK (event_id ~ '^[A-Za-z0-9_-]{1,64}$'),
    content_hash CHAR(64) NOT NULL,
    stream_id VARCHAR(64) NOT NULL,
    projection_version BIGINT NOT NULL,
    outcome VARCHAR(16) NOT NULL CHECK (outcome IN ('APPLIED','IGNORED_OLDER','IGNORED_SAME','CONFLICT')),
    received_at_utc TIMESTAMPTZ NOT NULL
);
CREATE INDEX discovery_inbox_received_idx ON discovery.inbox_events (received_at_utc);

-- Observable conflicts, with the payload kept for the operator (rare; Streaming sends them to its dead letter).
CREATE TABLE discovery.projection_conflicts (
    conflict_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id VARCHAR(64),
    stream_id VARCHAR(64) NOT NULL,
    projection_version BIGINT,
    reason VARCHAR(40) NOT NULL CHECK (reason IN ('EVENT_ID_REUSED','SAME_VERSION_DIFFERENT_CONTENT','CHANNEL_MISMATCH')),
    existing_hash CHAR(64),
    incoming_hash CHAR(64) NOT NULL,
    payload JSONB NOT NULL,
    detected_at_utc TIMESTAMPTZ NOT NULL
);

-- Outcome of the last consistent cut. last_cut_captured_at_utc proves the absence of a stream configuration.
CREATE TABLE discovery.reconciliation_state (
    singleton BOOLEAN PRIMARY KEY DEFAULT TRUE CHECK (singleton),
    last_snapshot_id VARCHAR(64),
    last_watermark BIGINT,
    last_cut_captured_at_utc TIMESTAMPTZ,
    last_success_at_utc TIMESTAMPTZ,
    last_attempt_at_utc TIMESTAMPTZ,
    last_failure_at_utc TIMESTAMPTZ,
    last_failure_code VARCHAR(64)
);
INSERT INTO discovery.reconciliation_state (singleton) VALUES (TRUE);

-- Frozen ordering for stable pagination of `streams`; only written when a result needs more than one page.
CREATE TABLE discovery.ranking_snapshots (
    snapshot_id UUID PRIMARY KEY,
    filter_hash CHAR(64) NOT NULL,
    stream_ids JSONB NOT NULL,
    created_at_utc TIMESTAMPTZ NOT NULL,
    expires_at_utc TIMESTAMPTZ NOT NULL,
    CHECK (expires_at_utc > created_at_utc)
);
CREATE INDEX discovery_ranking_expiry_idx ON discovery.ranking_snapshots (expires_at_utc);
