CREATE SCHEMA IF NOT EXISTS identity;

CREATE TABLE identity.registrations (
    registration_id VARCHAR(64) PRIMARY KEY,
    idempotency_key_hash CHAR(64) NOT NULL UNIQUE,
    request_fingerprint CHAR(64) NOT NULL,
    email VARCHAR(320),
    normalized_email VARCHAR(320),
    handle VARCHAR(25),
    password_hash VARCHAR(255),
    pending_since_utc TIMESTAMPTZ NOT NULL,
    pending_until_utc TIMESTAMPTZ NOT NULL,
    status VARCHAR(12) NOT NULL CHECK (status IN ('PENDING','ACTIVE','EXPIRED')),
    user_id VARCHAR(64) NOT NULL UNIQUE,
    channel_id VARCHAR(64),
    attempt_count INTEGER NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMPTZ NOT NULL,
    retain_until_utc TIMESTAMPTZ NOT NULL,
    compensation_complete BOOLEAN NOT NULL DEFAULT FALSE,
    CHECK (pending_until_utc > pending_since_utc),
    CHECK ((status='PENDING' AND email IS NOT NULL AND normalized_email IS NOT NULL AND handle IS NOT NULL AND password_hash IS NOT NULL)
        OR (status IN ('ACTIVE','EXPIRED') AND email IS NULL AND normalized_email IS NULL AND handle IS NULL AND password_hash IS NULL)),
    CHECK ((status='ACTIVE' AND channel_id IS NOT NULL) OR (status<>'ACTIVE' AND channel_id IS NULL))
);
CREATE INDEX identity_registration_retry_idx ON identity.registrations(next_attempt_at) WHERE status='PENDING';

CREATE TABLE identity.reservations (
    normalized_email VARCHAR(320) PRIMARY KEY,
    canonical_handle VARCHAR(25) NOT NULL UNIQUE,
    registration_id VARCHAR(64) NOT NULL UNIQUE,
    user_id VARCHAR(64) NOT NULL UNIQUE
);

CREATE TABLE identity.accounts (
    user_id VARCHAR(64) PRIMARY KEY,
    email VARCHAR(320) NOT NULL,
    normalized_email VARCHAR(320) NOT NULL UNIQUE,
    handle VARCHAR(25) NOT NULL,
    canonical_handle VARCHAR(25) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at_utc TIMESTAMPTZ NOT NULL
);

CREATE TABLE identity.sessions (
    session_id UUID PRIMARY KEY,
    user_id VARCHAR(64) NOT NULL REFERENCES identity.accounts(user_id) ON DELETE CASCADE,
    credential_hash CHAR(64) NOT NULL UNIQUE,
    created_at_utc TIMESTAMPTZ NOT NULL,
    expires_at_utc TIMESTAMPTZ NOT NULL,
    revoked_at_utc TIMESTAMPTZ,
    CHECK (expires_at_utc > created_at_utc)
);
CREATE INDEX identity_session_user_idx ON identity.sessions(user_id, expires_at_utc);

CREATE TABLE identity.rate_limit_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bucket_type VARCHAR(32) NOT NULL,
    bucket_hash CHAR(64) NOT NULL,
    source_key_hash CHAR(64),
    occurred_at_utc TIMESTAMPTZ NOT NULL
);
CREATE INDEX identity_rate_limit_window_idx ON identity.rate_limit_events(bucket_type,bucket_hash,occurred_at_utc DESC);
CREATE UNIQUE INDEX identity_registration_key_rate_idx ON identity.rate_limit_events(bucket_type,bucket_hash,source_key_hash) WHERE source_key_hash IS NOT NULL;

CREATE TABLE identity.outbox_events (
    event_id UUID PRIMARY KEY,
    event_type VARCHAR(80) NOT NULL,
    schema_version INTEGER NOT NULL,
    aggregate_id VARCHAR(128) NOT NULL,
    sequence_no BIGINT NOT NULL,
    occurred_at_utc TIMESTAMPTZ NOT NULL,
    payload JSONB NOT NULL,
    published_at_utc TIMESTAMPTZ,
    attempts INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX identity_outbox_pending_idx ON identity.outbox_events(occurred_at_utc) WHERE published_at_utc IS NULL;
